"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { BedDouble, Check, ChevronRight, Clock3, ExternalLink, MapPin, Navigation, Phone, Route, Utensils } from "lucide-react";

type Stop = { id:string; name:string; district:string; phone:string; address:string; lat:number; lon:number; time:string; duration:string; distance:string };
type DayPlan = { day:number; title:string; start:string; stay:string; distance:string; driving:string; depart:string; lunch:string; color:string; stops:Stop[]; startPoint:{name:string;lat:number;lon:number} };

const plans: DayPlan[] = [
  { day:1, title:"Pathanamthitta to High Range", start:"Thiruvalla", stay:"Mundakayam", distance:"96 km", driving:"2 hr 40 min", depart:"8:00 AM", lunch:"12:25–1:10 PM · Erumely", color:"#ea580c", startPoint:{name:"Thiruvalla",lat:9.3867448,lon:76.5762652}, stops:[
    {id:"omalloor",name:"Omalloor",district:"Pathanamthitta",phone:"9037854387",address:"Malankara Centre, near Darsana Auditorium, Adoor–Pathanamthitta Main Road, Omalloor, 689647",lat:9.2427057,lon:76.7558362,time:"9:00–9:45 AM",duration:"45 min visit",distance:"33 km"},
    {id:"thadiyoor",name:"Thadiyoor",district:"Pathanamthitta",phone:"9037854395",address:"Thottavallil Padamalayam Buildings, Bank Junction, Thadiyoor, 689545",lat:9.3838759,lon:76.7101824,time:"10:20–11:05 AM",duration:"45 min visit",distance:"22 km"},
    {id:"erumely",name:"Erumely",district:"Kottayam",phone:"9037854146",address:"Modern Dental Tower, Erumely–Mundakayam Road, Erumely, 686509",lat:9.4813743,lon:76.8448927,time:"11:45 AM–12:25 PM",duration:"40 min visit",distance:"27 km"},
    {id:"mundakayam",name:"Mundakayam",district:"Kottayam",phone:"9037854640",address:"Kuttenchirayil Building, Mundakayam P.O., Kottayam, 686513",lat:9.5441213,lon:76.876874,time:"1:30–2:15 PM",duration:"45 min visit",distance:"15 km"}
  ]},
  { day:2, title:"Mundakayam to Alappuzha", start:"Mundakayam", stay:"Alappuzha town", distance:"142 km", driving:"3 hr 30 min", depart:"8:00 AM", lunch:"12:45–1:30 PM · Mavelikara", color:"#0f766e", startPoint:{name:"Mundakayam",lat:9.5441213,lon:76.876874}, stops:[
    {id:"kattanam",name:"Kattanam",district:"Alappuzha",phone:"9037854214",address:"Palamoottil Building, K.P. Road, Pallickal P.O., via Kayamkulam, 690503",lat:9.1768788,lon:76.5633262,time:"10:00–10:45 AM",duration:"45 min visit",distance:"80 km"},
    {id:"kayamkulam",name:"Kayamkulam",district:"Alappuzha",phone:"9037854563",address:"Kadeesa Cathedral Complex, K.P. Road, Kayamkulam, 690502",lat:9.1723603,lon:76.500061,time:"11:00–11:40 AM",duration:"40 min visit",distance:"7 km"},
    {id:"mavelikara",name:"Mavelikara",district:"Alappuzha",phone:"9037854271",address:"Samuel Buildings, Nadakavu, Mavelikara, 690101",lat:9.2504893,lon:76.5402433,time:"12:00–12:45 PM",duration:"45 min visit",distance:"12 km"},
    {id:"kalarcode",name:"Kalarcode",district:"Alappuzha",phone:"9037854967",address:"Pathumuriyil, Kalarcode, Sanathanapuram P.O., Alappuzha, 688003",lat:9.4703974,lon:76.338313,time:"2:30–3:15 PM",duration:"45 min visit",distance:"42 km"}
  ]},
  { day:3, title:"Alappuzha Coastal Run", start:"Alappuzha town", stay:"Aroor / Kochi side", distance:"51 km", driving:"1 hr 35 min", depart:"9:00 AM", lunch:"12:15–1:00 PM · Cherthala", color:"#2563eb", startPoint:{name:"Alappuzha town",lat:9.4703974,lon:76.338313}, stops:[
    {id:"thathampally",name:"Thathampally",district:"Alappuzha",phone:"9037854915",address:"St. Michael's Building, St. Michael's Church Road, Thathampally, 688013",lat:9.503707,lon:76.3474787,time:"9:15–10:00 AM",duration:"45 min visit",distance:"5 km"},
    {id:"mannancherry",name:"Mannancherry",district:"Alappuzha",phone:"9037854902",address:"Building No. 4/D, Ponnad P.O., Mannancherry, 688538",lat:9.5720722,lon:76.3475691,time:"10:20–11:05 AM",duration:"45 min visit",distance:"9 km"},
    {id:"cherthala",name:"Cherthala",district:"Alappuzha",phone:"9037854120",address:"Sreemat Sudheendra Thirtha Navathi Smaraka Shopping Complex, near Manorama Junction, Cherthala, 688524",lat:9.6895997,lon:76.3341893,time:"11:30 AM–12:15 PM",duration:"45 min visit",distance:"15 km"},
    {id:"aroor",name:"Aroor",district:"Alappuzha",phone:"9037854606",address:"P.A.A. Building, Ward 16, Aroor P.O., Alappuzha, 688534",lat:9.8783108,lon:76.3038826,time:"1:40–2:25 PM",duration:"45 min visit",distance:"23 km"}
  ]}
];

declare global { interface Window { L?: any } }

function googleRoute(plan:DayPlan){const points=[plan.startPoint,...plan.stops];const origin=`${points[0].lat},${points[0].lon}`;const last=points.at(-1)!;const waypoints=points.slice(1,-1).map(p=>`${p.lat},${p.lon}`).join("|");return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${last.lat},${last.lon}&waypoints=${encodeURIComponent(waypoints)}&travelmode=driving`}

function MapPanel({plan}:{plan:DayPlan}){
  const node=useRef<HTMLDivElement>(null); const mapRef=useRef<any>(null);
  useEffect(()=>{let cancelled=false;const init=()=>{if(cancelled||!node.current||!window.L)return;if(mapRef.current)mapRef.current.remove();const L=window.L;const map=L.map(node.current,{zoomControl:true,scrollWheelZoom:false});mapRef.current=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);const points=[plan.startPoint,...plan.stops];const bounds=L.latLngBounds(points.map(p=>[p.lat,p.lon]));points.forEach((p,index)=>{const marker=L.divIcon({className:"route-marker",html:`<span style="background:${index===0?"#172554":plan.color}">${index===0?"S":index}</span>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([p.lat,p.lon],{icon:marker}).addTo(map).bindPopup(`<strong>${index===0?"Start: ":""}${p.name}</strong>`)});map.fitBounds(bounds,{padding:[32,32]});const coords=points.map(p=>`${p.lon},${p.lat}`).join(";");fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`).then(r=>r.json()).then((data:any)=>{if(!cancelled&&data.routes?.[0])L.geoJSON(data.routes[0].geometry,{style:{color:plan.color,weight:5,opacity:.9}}).addTo(map)}).catch(()=>L.polyline(points.map(p=>[p.lat,p.lon]),{color:plan.color,weight:4,dashArray:"8 8"}).addTo(map))};if(window.L)init();else{if(!document.querySelector("link[data-leaflet]")){const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";css.dataset.leaflet="true";document.head.appendChild(css)}const existing=document.querySelector<HTMLScriptElement>("script[data-leaflet]");if(existing)existing.addEventListener("load",init,{once:true});else{const script=document.createElement("script");script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.dataset.leaflet="true";script.onload=init;document.body.appendChild(script)}}return()=>{cancelled=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[plan]);
  return <div ref={node} className="h-full min-h-[360px] w-full" aria-label={`Day ${plan.day} route map`}/>;
}

export default function Home(){
  const[activeDay,setActiveDay]=useState(1);const[visited,setVisited]=useState<string[]>([]);const plan=plans[activeDay-1];
  useEffect(()=>{try{setVisited(JSON.parse(localStorage.getItem("thiruvalla-route-progress")||"[]"))}catch{}},[]);
  useEffect(()=>{localStorage.setItem("thiruvalla-route-progress",JSON.stringify(visited))},[visited]);
  const allStops=useMemo(()=>plans.flatMap(p=>p.stops),[]);const nextStop=allStops.find(s=>!visited.includes(s.id));const toggle=(id:string)=>setVisited(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  return <main className="min-h-screen bg-[#f4f7fb] text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-5 px-5 py-5 lg:px-8">
      <div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-blue-950 text-white"><Route size={23}/></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-700">Field Visit Plan</p><h1 className="text-xl font-bold tracking-tight sm:text-2xl">Thiruvalla · 3-Day Route</h1></div></div>
      <div className="flex min-w-[260px] items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><div className="min-w-0 flex-1"><div className="flex justify-between text-sm font-semibold"><span>Trip progress</span><span>{visited.length}/12</span></div><Progress value={(visited.length/12)*100} className="mt-2 h-2"/></div><div className="grid size-9 place-items-center rounded-lg bg-white text-blue-800 shadow-sm"><Check size={18}/></div></div>
    </div></header>
    <section className="mx-auto max-w-[1500px] px-5 py-6 lg:px-8">
      <div className="mb-5 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mb-1 text-sm font-medium text-slate-500">12 selected destinations · approximately 289 km</p><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Plan each day. Finish every visit before 5 PM.</h2></div>{nextStop&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm"><span className="text-blue-700">Next pending</span><strong className="ml-2 text-blue-950">{nextStop.name}</strong></div>}</div>
      <Tabs value={String(activeDay)} onValueChange={v=>setActiveDay(Number(v))}><TabsList className="mb-5 grid h-auto w-full grid-cols-3 rounded-xl bg-slate-200/70 p-1.5 md:w-[520px]">{plans.map(item=><TabsTrigger key={item.day} value={String(item.day)} className="min-h-12 rounded-lg px-3 text-sm data-[state=active]:bg-white data-[state=active]:shadow-sm"><span className="font-bold">Day {item.day}</span><span className="ml-2 hidden text-slate-500 sm:inline">{item.stops.length} stops</span></TabsTrigger>)}</TabsList></Tabs>
      <div className="grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_16px_40px_rgba(15,23,42,.08)] xl:grid-cols-[minmax(0,1.15fr)_minmax(440px,.85fr)]">
        <div className="relative min-h-[430px] border-b border-slate-200 xl:border-b-0 xl:border-r"><MapPanel plan={plan}/><div className="absolute bottom-4 left-4 z-[500] rounded-xl border border-white/60 bg-white/95 px-4 py-3 shadow-lg backdrop-blur"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Day {plan.day} route</p><p className="mt-1 font-bold">{plan.start} <ChevronRight className="inline" size={15}/> {plan.stay}</p></div></div>
        <aside className="flex max-h-[760px] flex-col"><div className="border-b border-slate-200 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold" style={{color:plan.color}}>DAY {plan.day}</p><h3 className="mt-1 text-xl font-bold">{plan.title}</h3></div><a className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-950 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-900" href={googleRoute(plan)} target="_blank" rel="noreferrer">Open full route <ExternalLink size={16}/></a></div>
          <div className="mt-5 grid grid-cols-3 gap-3"><Metric icon={<Navigation size={17}/>} label="Distance" value={plan.distance}/><Metric icon={<Clock3 size={17}/>} label="Driving" value={plan.driving}/><Metric icon={<BedDouble size={17}/>} label="Stay" value={plan.stay}/></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span><strong className="text-slate-900">Depart:</strong> {plan.depart}</span><span className="inline-flex items-center gap-1.5"><Utensils size={15}/><strong className="text-slate-900">Lunch:</strong> {plan.lunch}</span></div></div>
          <div className="overflow-y-auto p-5 sm:p-6"><div className="relative space-y-4 before:absolute before:bottom-8 before:left-[17px] before:top-8 before:w-px before:bg-slate-200">{plan.stops.map((stop,index)=>{const done=visited.includes(stop.id);return <article key={stop.id} className={`relative grid grid-cols-[36px_1fr] gap-3 rounded-xl border p-4 transition ${done?"border-emerald-200 bg-emerald-50/70":"border-slate-200 bg-white hover:border-slate-300"}`}>
            <button onClick={()=>toggle(stop.id)} aria-label={done?`Mark ${stop.name} pending`:`Mark ${stop.name} visited`} className={`relative z-10 grid size-9 place-items-center rounded-full border-4 border-white text-sm font-bold text-white shadow-sm ${done?"bg-emerald-600":""}`} style={!done?{background:plan.color}:undefined}>{done?<Check size={17}/>:index+1}</button>
            <div className="min-w-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className={`text-lg font-bold ${done?"line-through decoration-emerald-600/50":""}`}>{stop.name}</h4><p className="text-sm text-slate-500">{stop.district} · {stop.distance} from previous</p></div><span className="rounded-md bg-slate-100 px-2.5 py-1 text-sm font-semibold text-slate-700">{stop.time}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{stop.address}</p><div className="mt-3 flex flex-wrap gap-2"><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold hover:bg-slate-50" href={`tel:${stop.phone}`}><Phone size={15}/>{stop.phone}</a><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold hover:bg-slate-50" href={`https://www.google.com/maps/search/?api=1&query=${stop.lat},${stop.lon}`} target="_blank" rel="noreferrer"><MapPin size={15}/>Navigate</a><span className="inline-flex min-h-10 items-center text-sm text-slate-500">{stop.duration}</span></div></div>
          </article>})}</div><div className="mt-5 flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><Clock3 className="mt-0.5 shrink-0" size={18}/><p><strong>Daily buffer included.</strong> Timings allow for traffic, lunch and short delays. All scheduled visits finish well before 5:00 PM.</p></div></div>
        </aside>
      </div>
    </section>
  </main>
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="flex items-center gap-1.5 text-xs font-medium text-slate-500">{icon}{label}</div><p className="mt-1 truncate text-sm font-bold text-slate-950 sm:text-base">{value}</p></div>}
