"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { BedDouble, Check, ChevronRight, Clock3, ExternalLink, MapPin, Navigation, Phone, Route, Utensils } from "lucide-react";

type Stop = { id:string; name:string; district:string; phone:string; address:string; lat:number; lon:number; time:string; duration:string; distance:string };
type DayPlan = { day:number; title:string; start:string; stay:string; distance:string; driving:string; depart:string; lunch:string; color:string; stops:Stop[]; startPoint:{name:string;lat:number;lon:number} };

// Town-level map positions; address-based navigation below identifies the branch.
const plans: DayPlan[] = [
  {day:1,title:"Kottayam to Mundakayam",start:"Kottayam",stay:"Mundakayam",distance:"~65 km",driving:"~3 hr by bus",depart:"9:00 AM",lunch:"12:45–1:30 PM · Pampady",color:"#ea580c",startPoint:{name:"Kottayam",lat:9.5916,lon:76.5222},stops:[
    {id:"chingavanam",name:"Chingavanam",district:"Kottayam",phone:"9037854764",address:"Ward No. II/134C, Kunutharayil Arcade, M.C. Road, Chingavanam P.O., 686531",lat:9.531,lon:76.536,time:"10:00–10:45 AM",duration:"45 min visit",distance:"~10 km"},
    {id:"pampady",name:"Pampady",district:"Kottayam",phone:"9037854212",address:"Do. No. 72, Ward No. VII, Rhema Centre, K.K. Road, Vattamalappady, Pampady P.O., 686502",lat:9.566,lon:76.64,time:"12:00–12:45 PM",duration:"45 min visit",distance:"~22 km"},
    {id:"mundakayam",name:"Mundakayam",district:"Kottayam",phone:"9037854640",address:"Do. No. 341(C), Kuttenchirayil Building, Mundakayam P.O., 686513",lat:9.5441213,lon:76.876874,time:"2:45–3:30 PM",duration:"45 min visit",distance:"~33 km"}
  ]},
  {day:2,title:"Erumely to Pala",start:"Mundakayam",stay:"Pala town",distance:"~65 km",driving:"~3–3½ hr by bus",depart:"9:00 AM",lunch:"11:45 AM–12:30 PM · Erumely",color:"#0f766e",startPoint:{name:"Mundakayam",lat:9.5441213,lon:76.876874},stops:[
    {id:"erumely",name:"Erumely",district:"Kottayam",phone:"9037854146",address:"Do. No. B, Ward No. XX, Modern Dental Tower, Erumely–Mundakayam Road, Erumely P.O., 686509",lat:9.4813743,lon:76.8448927,time:"10:00–10:45 AM",duration:"45 min visit",distance:"~15 km"},
    {id:"bharananganam",name:"Bharananganam",district:"Kottayam",phone:"9037854010",address:"Do. No. 1/243–249, Ward No. VII, Njayarkulam Buildings, Pala–Erattupetta Main Road, opposite St. Alphonsa Shrine Church, Bharananganam P.O., 686578",lat:9.702,lon:76.724,time:"2:00–2:45 PM",duration:"45 min visit",distance:"~45 km"},
    {id:"palai",name:"Palai (Pala)",district:"Kottayam",phone:"9037854062",address:"Door No. 11/39-3, Ward No. 11, Kuthivalachel Building, Pala–Erattupetta Road, Pala P.O., Meenachil Taluk, 686575",lat:9.713,lon:76.686,time:"3:15–4:00 PM",duration:"45 min visit",distance:"~5 km"}
  ]},
  {day:3,title:"Pala to Kallara",start:"Pala town",stay:"Finish at Kallara",distance:"~55 km",driving:"~2½–3 hr by bus",depart:"9:00 AM",lunch:"1:00–1:45 PM · Athirampuzha",color:"#2563eb",startPoint:{name:"Pala town",lat:9.713,lon:76.686},stops:[
    {id:"pravithanam",name:"Pravithanam",district:"Kottayam",phone:"9037854183",address:"Do. No. 74/F, Ward No. 10, Chooranolickal Arcade, Anthinad Junction, Pravithanam, 686651",lat:9.761,lon:76.689,time:"10:00–10:45 AM",duration:"45 min visit",distance:"~8 km"},
    {id:"athirampuzha",name:"Athirampuzha",district:"Kottayam",phone:"9037854116",address:"Pannackal Buildings, Central Junction, Athirampuzha, 686562",lat:9.668,lon:76.532,time:"12:15–1:00 PM",duration:"45 min visit",distance:"~32 km"},
    {id:"kallara",name:"Kallara",district:"Kottayam",phone:"9037854210",address:"Niravathaniyil Building, Kallara South P.O., Kallara, 686611",lat:9.726,lon:76.477,time:"2:45–3:30 PM",duration:"45 min visit",distance:"~15 km"}
  ]}
];

declare global { interface Window { L?: any } }

function googleRoute(plan:DayPlan){const points=[plan.startPoint,...plan.stops];const origin=`${points[0].lat},${points[0].lon}`;const last=points.at(-1)!;const waypoints=points.slice(1,-1).map(p=>`${p.lat},${p.lon}`).join("|");return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${last.lat},${last.lon}&waypoints=${encodeURIComponent(waypoints)}&travelmode=driving`}

function MapPanel({plan}:{plan:DayPlan}){
  const node=useRef<HTMLDivElement>(null); const mapRef=useRef<any>(null);
  useEffect(()=>{let cancelled=false;const init=()=>{if(cancelled||!node.current||!window.L)return;if(mapRef.current)mapRef.current.remove();const L=window.L;const map=L.map(node.current,{zoomControl:false,scrollWheelZoom:false,dragging:false,touchZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false});mapRef.current=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);const points=[plan.startPoint,...plan.stops];const bounds=L.latLngBounds(points.map(p=>[p.lat,p.lon]));points.forEach((p,index)=>{const marker=L.divIcon({className:"route-marker",html:`<span style="background:${index===0?"#172554":plan.color}">${index===0?"S":index}</span>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([p.lat,p.lon],{icon:marker,interactive:false}).addTo(map)});map.fitBounds(bounds,{padding:[24,24]});const coords=points.map(p=>`${p.lon},${p.lat}`).join(";");fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`).then(r=>r.json()).then((data:any)=>{if(!cancelled&&data.routes?.[0])L.geoJSON(data.routes[0].geometry,{style:{color:plan.color,weight:5,opacity:.9},interactive:false}).addTo(map)}).catch(()=>L.polyline(points.map(p=>[p.lat,p.lon]),{color:plan.color,weight:4,dashArray:"8 8",interactive:false}).addTo(map))};if(window.L)init();else{if(!document.querySelector("link[data-leaflet]")){const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";css.dataset.leaflet="true";document.head.appendChild(css)}const existing=document.querySelector<HTMLScriptElement>("script[data-leaflet]");if(existing)existing.addEventListener("load",init,{once:true});else{const script=document.createElement("script");script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.dataset.leaflet="true";script.onload=init;document.body.appendChild(script)}}return()=>{cancelled=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[plan]);
  return <div ref={node} className="h-full min-h-0 w-full" aria-label={`Day ${plan.day} route map`}/>;
}

export default function Home(){
  const[activeDay,setActiveDay]=useState(1);const[visited,setVisited]=useState<string[]>([]);const plan=plans[activeDay-1];
  useEffect(()=>{try{setVisited(JSON.parse(localStorage.getItem("kottayam-nine-route-progress")||"[]"))}catch{}},[]);
  useEffect(()=>{localStorage.setItem("kottayam-nine-route-progress",JSON.stringify(visited))},[visited]);
  const allStops=useMemo(()=>plans.flatMap(p=>p.stops),[]);const nextStop=allStops.find(s=>!visited.includes(s.id));const toggle=(id:string)=>setVisited(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  return <main className="min-h-screen bg-[#f4f7fb] text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-5 px-5 py-5 lg:px-8">
      <div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-blue-950 text-white"><Route size={23}/></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-700">Field Visit Plan</p><h1 className="text-xl font-bold tracking-tight sm:text-2xl">Kottayam · 3-Day Route</h1></div></div>
      <div className="flex min-w-[260px] items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><div className="min-w-0 flex-1"><div className="flex justify-between text-sm font-semibold"><span>Trip progress</span><span>{visited.length}/9</span></div><Progress value={(visited.length/9)*100} className="mt-2 h-2"/></div><div className="grid size-9 place-items-center rounded-lg bg-white text-blue-800 shadow-sm"><Check size={18}/></div></div>
    </div></header>
    <section className="mx-auto max-w-[1500px] px-5 py-6 lg:px-8">
      <div className="mb-5 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mb-1 text-sm font-medium text-slate-500">Starts in Kottayam · 9 branches · approximately 185 km · bus travel estimates</p><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Three branches maximum. Every visit before 5 PM.</h2></div>{nextStop&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm"><span className="text-blue-700">Next pending</span><strong className="ml-2 text-blue-950">{nextStop.name}</strong></div>}</div>
      <Tabs value={String(activeDay)} onValueChange={v=>setActiveDay(Number(v))}><TabsList className="mb-5 grid h-[52px] w-full grid-cols-3 rounded-xl bg-slate-200/70 p-1.5 md:w-[660px]">{plans.map(item=><TabsTrigger key={item.day} value={String(item.day)} className="h-full min-h-0 rounded-lg px-1 text-sm data-[state=active]:bg-white data-[state=active]:shadow-sm sm:px-3"><span className="font-bold">Day {item.day}</span><span className="ml-2 hidden text-slate-500 md:inline">{item.stops.length} stops</span></TabsTrigger>)}</TabsList></Tabs>
      <div className="grid overflow-visible rounded-2xl border border-slate-200 bg-white shadow-[0_16px_40px_rgba(15,23,42,.08)] xl:grid-cols-[minmax(0,1.15fr)_minmax(440px,.85fr)] xl:items-start">
        <div onWheel={event=>{event.preventDefault();window.scrollBy(0,event.deltaY)}} className="relative h-[320px] min-h-0 overflow-hidden rounded-t-2xl border-b border-slate-200 sm:h-[430px] xl:sticky xl:top-4 xl:h-[calc(100vh-2rem)] xl:max-h-[760px] xl:min-h-[560px] xl:rounded-l-2xl xl:rounded-tr-none xl:border-b-0 xl:border-r"><MapPanel plan={plan}/><div className="pointer-events-none absolute bottom-3 left-3 right-3 z-[500] max-w-fit rounded-xl border border-white/60 bg-white/95 px-4 py-3 shadow-lg backdrop-blur sm:bottom-4 sm:left-4 sm:right-auto"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Day {plan.day} route</p><p className="mt-1 font-bold">{plan.start} <ChevronRight className="inline" size={15}/> {plan.stay}</p></div></div>
        <aside className="flex min-w-0 flex-col"><div className="border-b border-slate-200 p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold" style={{color:plan.color}}>DAY {plan.day}</p><h3 className="mt-1 text-xl font-bold">{plan.title}</h3></div><a className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-blue-950 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-900 sm:w-auto" href={googleRoute(plan)} target="_blank" rel="noreferrer">Open full route <ExternalLink size={16}/></a></div>
          <div className="mt-5 grid grid-cols-3 gap-3"><Metric icon={<Navigation size={17}/>} label="Distance" value={plan.distance}/><Metric icon={<Clock3 size={17}/>} label="Bus travel" value={plan.driving}/><Metric icon={<BedDouble size={17}/>} label="Stay" value={plan.stay}/></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span><strong className="text-slate-900">Depart:</strong> {plan.depart}</span><span className="inline-flex items-center gap-1.5"><Utensils size={15}/><strong className="text-slate-900">Lunch:</strong> {plan.lunch}</span></div></div>
          <div className="p-4 sm:p-6"><div className="relative space-y-4 before:absolute before:bottom-8 before:left-[17px] before:top-8 before:w-px before:bg-slate-200">{plan.stops.map((stop,index)=>{const done=visited.includes(stop.id);return <article key={stop.id} className={`relative grid grid-cols-[36px_minmax(0,1fr)] gap-3 rounded-xl border p-3 transition sm:p-4 ${done?"border-emerald-200 bg-emerald-50/70":"border-slate-200 bg-white hover:border-slate-300"}`}>
            <button onClick={()=>toggle(stop.id)} aria-label={done?`Mark ${stop.name} pending`:`Mark ${stop.name} visited`} className={`relative z-10 grid size-9 place-items-center rounded-full border-4 border-white text-sm font-bold text-white shadow-sm ${done?"bg-emerald-600":""}`} style={!done?{background:plan.color}:undefined}>{done?<Check size={17}/>:index+1}</button>
            <div className="min-w-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className={`text-lg font-bold ${done?"line-through decoration-emerald-600/50":""}`}>{stop.name}</h4><p className="text-sm text-slate-500">{stop.district} · {stop.distance} from previous</p></div><span className="rounded-md bg-slate-100 px-2.5 py-1 text-sm font-semibold text-slate-700">{stop.time}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{stop.address}</p><div className="mt-3 flex flex-wrap gap-2"><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold hover:bg-slate-50" href={`tel:${stop.phone}`}><Phone size={15}/>{stop.phone}</a><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold hover:bg-slate-50" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`South Indian Bank ${stop.name}, ${stop.address}`)}`} target="_blank" rel="noreferrer"><MapPin size={15}/>Navigate</a><span className="inline-flex min-h-10 items-center text-sm text-slate-500">{stop.duration}</span></div></div>
          </article>})}</div><div className="mt-5 flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><Clock3 className="mt-0.5 shrink-0" size={18}/><p><strong>Bus travel estimates — confirm locally.</strong> Allow for bus waits, transfers and short auto rides. Day 1: connect via Kottayam for Pampady; Day 2: via Kanjirappally and Erattupetta for Bharananganam; Day 3: via Pala and Ettumanoor for Athirampuzha. Map pins are approximate town locations; Navigate searches the branch address. Full route shows a road overview, not a bus timetable. Confirm branch access and holidays before travelling. Take a 15-minute tea/rest break after the second visit. All visits finish by 4 PM.</p></div></div>
        </aside>
      </div>
    </section>
  </main>
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="flex items-center gap-1.5 text-xs font-medium text-slate-500">{icon}{label}</div><p className="mt-1 truncate text-sm font-bold text-slate-950 sm:text-base">{value}</p></div>}
